### ISSUE TITLE
storage/localstore: Possible deadlock on TestDB_SubscribePull* tests

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1245]
`TestDB_SubscribePull* ` test always time out on Travis if `-race` is present with high goroutine wait time. Investigation is needed.

**Stacktrace**

```
=== RUN   TestDB_SubscribePull_since
panic: test timed out after 20m0s
goroutine 109597 [running]:
testing.(*M).startAlarm.func1()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1296 +0x13a
created by time.goFunc
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/time/sleep.go:172 +0x52
goroutine 1 [chan receive, 19 minutes]:
testing.(*T).Run(0xc0000fc100, 0xa901f8, 0x1a, 0xaa1880, 0xc0000cbc01)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:879 +0x692
testing.runTests.func1(0xc0000fc100)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc0000fc100, 0xc0000cbd88)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x163
testing.runTests(0xc00000c940, 0x102f8c0, 0x1c, 0x1c, 0xc0000cbe30)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000112000, 0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:104 +0x222
goroutine 32568 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc00088a000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x16b
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x7c0
goroutine 32573 [select, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.(*DB).writeGCSizeWorker(0xc0000ea580)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/gc.go:247 +0x139
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.New
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/localstore.go:354 +0x1bf5
goroutine 39661 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000546400, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 23 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000128080, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 32585 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112200, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 35849 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112200, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 19103 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000694000, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 39170 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000113180, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 39578 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112080, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 32574 [select, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.(*DB).collectGarbageWorker(0xc0000ea580)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/gc.go:121 +0x131
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.New
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/localstore.go:356 +0x1c2e
goroutine 9776 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112200, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 106001 [semacquire, 19 minutes]:
sync.runtime_SemacquireMutex(0xc00153c59c, 0x900000000)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc00153c598)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/sync/mutex.go:134 +0x153
github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since.func2(0xf, 0xaa1901, 0xb17de0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:179 +0x1c9
github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since(0xc001ac9200)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:229 +0x761
testing.tRunner(0xc001ac9200, 0xaa1880)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:878 +0x65a
goroutine 105952 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000113280, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 106069 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000084000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:825 +0x356
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x957
goroutine 109669 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0x6, 0xc001fb75c0, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:460 +0x66c
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
goroutine 32569 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00088a000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x170
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x7e5
goroutine 26073 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112200, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 32572 [select]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112280, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:317 +0x1461
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 109657 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0xc000122a00, 0xc001fb6f00, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:470 +0x75
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
goroutine 106067 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000084000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x16b
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x7c0
goroutine 109663 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0xc000122a03, 0xc001fb7260, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:470 +0x75
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
goroutine 32570 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc00088a000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:825 +0x356
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x957
goroutine 39573 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112a80, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 39414 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000546280, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 32571 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc00088a000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:762 +0x1aa
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x97c
goroutine 32257 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc00055e000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1a6
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2d0
goroutine 39490 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000546000, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 39229 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112080, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 106071 [select]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000546000, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:317 +0x1461
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 39323 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112680, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 106070 [select, 19 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000084000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:762 +0x1aa
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x97c
goroutine 105840 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000546000, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 106082 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc00055e380)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1a6
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2d0
goroutine 106068 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000084000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x170
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x7e5
goroutine 109659 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0xc000122a01, 0xc001fb7020, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:470 +0x75
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
goroutine 109661 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0xc000122a02, 0xc001fb7140, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:470 +0x75
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
goroutine 106073 [select, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.(*DB).collectGarbageWorker(0xc0000ea000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/gc.go:121 +0x131
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.New
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/localstore.go:356 +0x1c2e
goroutine 106072 [select, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.(*DB).writeGCSizeWorker(0xc0000ea000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/gc.go:247 +0x139
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.New
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/localstore.go:354 +0x1bf5
goroutine 105925 [chan send (nil chan), 19 minutes]:
github.com/ethereum/go-ethereum/swarm/shed.(*DB).meter(0xc000112780, 0x2540be400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:328 +0x1fad
created by github.com/ethereum/go-ethereum/swarm/shed.NewDB
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/shed/db.go:96 +0x21e
goroutine 109673 [chan send, 19 minutes]:
github.com/ethereum/go-ethereum/swarm/storage/localstore.readPullSubscriptionBin(0xb17de0, 0xc001547a40, 0xc000122b08, 0xc001fb7800, 0xc000afd290, 0xc00153c598, 0xc001fb6ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:470 +0x75
created by github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:224 +0x570
FAIL	github.com/ethereum/go-ethereum/swarm/storage/localstore	1200.053s
```

**Comment by janos** [comment]
This is very strange, indeed. I have looked at some goroutines that were waiting for 19 minutes and something is not clear to me:

Could you get what is the commit against tests are run? I can not find meaningful code (on master and ci-race-detector-handle-failing-tests) for https://github.com/ethersphere/go-ethereum/blob/master/swarm/storage/localstore/subscription_pull_test.go#L179 and https://github.com/ethersphere/go-ethereum/blob/master/swarm/storage/localstore/subscription_pull_test.go#L229.

```
github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since.func2(0xf, 0xaa1901, 0xb17de0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:179 +0x1c9
github.com/ethereum/go-ethereum/swarm/storage/localstore.TestDB_SubscribePull_since(0xc001ac9200)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/localstore/subscription_pull_test.go:229 +0x761
testing.tRunner(0xc001ac9200, 0xaa1880)
```

swarm/storage/localstore/subscription_pull_test.go:470 is waiting for 19 minutes but context in that select case have a timeout for 10 seconds.

A Shed metrics goroutine wait [chan send (nil chan), 19 minutes] in swarm/shed/db.go:328 should not happen.

**Comment by frncmx** [comment]
The job run on my fork on a tmp branch. 

This was the commit: https://github.com/frncmx/go-ethereum/commit/049f5cc8972b2a2cc4859d7c31829428be09372e
This was the job: https://travis-ci.org/frncmx/go-ethereum/jobs/496080234

**Comment by janos** [comment]
Thanks, that makes much more sense. :)
