### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1281]
Detected on our public staging cluster: 

`swarm-public-2` , `swarm-public-4` and `swarm-public-8` started throwing the following panic:

```
panic: runtime error: index out of range

goroutine 165 [running]:
github.com/ethereum/go-ethereum/swarm/network.sanitizeEnodeRemote(0x10d27a0, 0xc000382180, 0xc00013edb0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:233 +0x3ba
github.com/ethereum/go-ethereum/swarm/network.(*Bzz).performHandshake(0xc0000b6a80, 0xc010e8a8a0, 0xc010f30f50, 0x0, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:220 +0x1df
github.com/ethereum/go-ethereum/swarm/network.(*Bzz).runBzz(0xc0000b6a80, 0xc011000840, 0x10d1760, 0xc0110d6120, 0x0, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:250 +0x422
github.com/ethereum/go-ethereum/swarm/network.(*Bzz).runBzz-fm(0xc011000840, 0x10d1760, 0xc0110d6120, 0x0, 0xc00043ae47)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:136 +0x48
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc0110d6120, 0xc011000840, 0x10d1760, 0xc0110d6120)
        /go/src/github.com/ethereum/go-ethereum/p2p/peer.go:361 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go/src/github.com/ethereum/go-ethereum/p2p/peer.go:360 +0x1fb
```

**Comment by janos** [comment]
This is actually desired behaviour. Maybe it is better to actually log unmatched value by regexp instead to just panic to be able to adjust the regexp pattern. Related discussions https://github.com/ethersphere/go-ethereum/pull/1224#discussion_r258349231 https://github.com/ethereum/go-ethereum/pull/19137#discussion_r258398610. Probably the address is ipv6 but that can be just a guess.

**Comment by skylenet** [comment]
This will probably disappear when implementing: https://github.com/ethersphere/go-ethereum/issues/1275

**Comment by skylenet** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/19193
