### ISSUE TITLE
Fix "panic: close of nil channel" at `/swarm/network` tests

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#259]
```
panic: close of nil channel
goroutine 48 [running]:
github.com/ethereum/go-ethereum/swarm/network.newBzzBaseTester.func1(0xc42029b1a0, 0x11038e0, 0xc420010050)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/network/protocol_test.go:99 +0x13f
github.com/ethereum/go-ethereum/swarm/network.newBzzBaseTester.func2(0xc42029f5c0, 0x11080a0, 0xc420119b90, 0xc420272748, 0xc42029e180)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/network/protocol_test.go:103 +0x1a1
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc420119ab0, 0xc42029f5c0, 0x11080a0, 0xc420119b90)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x228
FAIL	github.com/ethereum/go-ethereum/swarm/network	1.044s
```

as seen at https://travis-ci.org/ethersphere/go-ethereum/jobs/343431369

**Comment by nonsense** [comment]
This was addressed by https://github.com/ethersphere/go-ethereum/pull/212
