### ISSUE TITLE
Fix and enable TestRandomBrokenData

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#289]
This is failing on `master` (abed63c38fe817e73ccbc8f123aee044d10d1711) on AppVeyor

```
--- FAIL: TestRandomBrokenData (0.00s)
433    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
434    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
435    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
436    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
437    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
438    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
439    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
440    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
441    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
442    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
443    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
444    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
445    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
446    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
447    chunker_test.go:191:  Key = 0000000000000000000000000000000000000000000000000000000000000000
448panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
449    panic: sync: WaitGroup is reused before previous Wait has returned
450
451goroutine 84555 [running]:
452testing.tRunner.func1(0xc0420d01e0)
453    C:/go/src/testing/testing.go:711 +0x2d9
454panic(0x658720, 0x6e4900)
455    C:/go/src/runtime/panic.go:491 +0x291
456sync.(*WaitGroup).Wait(0xc04200fec0)
457    C:/go/src/sync/waitgroup.go:133 +0xc2
458github.com/ethereum/go-ethereum/swarm/storage.(*chunkerTester).Split(0xc0431ac740, 0x81dc00, 0xc042044900, 0x81c900, 0xc042092ba0, 0x1e240, 0xc042152d20, 0xc04200fec0, 0x81c740, 0xc0420b8480, ...)
459    C:/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/chunker_test.go:85 +0x214
460github.com/ethereum/go-ethereum/swarm/storage.testRandomBrokenData(0x81dc00, 0xc042044900, 0x1e240, 0xc0431ac740)
461    C:/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/chunker_test.go:187 +0x3f2
462github.com/ethereum/go-ethereum/swarm/storage.TestRandomBrokenData(0xc0420d01e0)
463    C:/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/chunker_test.go:371 +0x148
464testing.tRunner(0xc0420d01e0, 0x6c55e8)
465    C:/go/src/testing/testing.go:746 +0xd7
466created by testing.(*T).Run
467    C:/go/src/testing/testing.go:789 +0x2e5
468FAIL    github.com/ethereum/go-ethereum/swarm/storage    0.446s
```

**Comment by nonsense** [comment]
https://ci.appveyor.com/project/ethereum/go-ethereum/build/master.5609/job/0v8wf82422vix198#L432
