### ISSUE TITLE
Fix panic

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#298]
```
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! write tcp 172.17.0.4:30401->137.116.217.142:46730: write: connection reset by peer
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|18:37:21|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xc21fdf]

goroutine 91 [running]:
github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Retrieve(0x0, 0xc421852fc0, 0xc420027000, 0xf08997)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/stream.go:207 +0x2f
github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Retrieve-fm(0xc421852fc0, 0xc421633440, 0x20)
        /go/src/github.com/ethereum/go-ethereum/swarm/swarm.go:150 +0x34
github.com/ethereum/go-ethereum/swarm/storage.(*NetStore).Get(0xc42028c970, 0xc421633440, 0x20, 0x20, 0xc421852fc0, 0x0, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/netstore.go:57 +0x28e
github.com/ethereum/go-ethereum/swarm/storage.(*DPA).retrieveWorker(0xc420068640)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/dpa.go:142 +0xbb
created by github.com/ethereum/go-ethereum/swarm/storage.(*DPA).retrieveLoop
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/dpa.go:135 +0x50
```

**Comment by nonsense** [comment]
This was due to incorrectly replacing DBAPI with NetStore. Reverting the commit solved it: https://github.com/ethersphere/go-ethereum/pull/300
