### ISSUE TITLE
Fix panix

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#301]
```
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
ERROR[03-05|22:31:07|swarm/network/stream/stream.go:305] Error in RequestSubsciption! shutting down
panic: interface conversion: network.OverlayConn is *network.discPeer, not *network.BzzPeer

goroutine 104 [running]:
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).RequestFromPeers.func1(0x16d9aa0, 0xc4218da480, 0x4, 0x16d9a01, 0xc4218da480)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:220 +0x574
github.com/ethereum/go-ethereum/swarm/network.(*Kademlia).eachConn.func1(0xe315e0, 0xc421816f00, 0x4, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/kademlia.go:356 +0xb2
github.com/ethereum/go-ethereum/pot.(*Pot).eachNeighbour(0xc421306100, 0xd682c0, 0xc4218ed060, 0xc420294dd0, 0xc430795cd8, 0x1)
        /go/src/github.com/ethereum/go-ethereum/pot/pot.go:592 +0xec
github.com/ethereum/go-ethereum/pot.(*Pot).eachNeighbour(0xc42182b080, 0xd682c0, 0xc4218ed060, 0xc420294dd0, 0xc430795cd8, 0x0)
        /go/src/github.com/ethereum/go-ethereum/pot/pot.go:582 +0x318
github.com/ethereum/go-ethereum/pot.(*Pot).eachNeighbour(0xc42166d840, 0xd682c0, 0xc4218ed060, 0xc420294dd0, 0xc430795cd8, 0xc4218ed060)
        /go/src/github.com/ethereum/go-ethereum/pot/pot.go:582 +0x318
github.com/ethereum/go-ethereum/pot.(*Pot).EachNeighbour(0xc42166d840, 0xd682c0, 0xc4218ed060, 0xc420294dd0, 0xc4213e1cd8, 0xc4213e1cf8)
        /go/src/github.com/ethereum/go-ethereum/pot/pot.go:566 +0x53
github.com/ethereum/go-ethereum/swarm/network.(*Kademlia).eachConn(0xc420237590, 0xc421651e20, 0x20, 0x20, 0xff, 0xc4213e9800)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/kademlia.go:357 +0x12a
github.com/ethereum/go-ethereum/swarm/network.(*Kademlia).EachConn(0xc420237590, 0xc421651e20, 0x20, 0x20, 0xff, 0xc4213e9800)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/kademlia.go:344 +0x99
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).RequestFromPeers(0xc4202a1a10, 0xc421651e20, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc420028800)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:239 +0x17d
github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Retrieve(0xc4201e4140, 0xc4213e9740, 0x1a2e840, 0xf08a17)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/stream.go:207 +0x75
github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Retrieve-fm(0xc4213e9740, 0xc421651e20, 0x20)
        /go/src/github.com/ethereum/go-ethereum/swarm/swarm.go:161 +0x34
github.com/ethereum/go-ethereum/swarm/storage.(*NetStore).Get(0xc42022c9c0, 0xc421651e20, 0x20, 0x20, 0xc4213e9740, 0x0, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/netstore.go:57 +0x28e
github.com/ethereum/go-ethereum/swarm/storage.(*DPA).retrieveWorker(0xc4202372c0)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/dpa.go:142 +0xbb
created by github.com/ethereum/go-ethereum/swarm/storage.(*DPA).retrieveLoop
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/dpa.go:135 +0x50
```

**Comment by nonsense** [comment]
Fixed at https://github.com/ethersphere/go-ethereum/pull/171/commits/cdca2574024db10568eb581f3b2f0cb15abb69fc
