### ISSUE TITLE
[Swarm] "panic: close of closed channel" when processing PSS messages

### ISSUE THREAD

**Issue by 4h0q** [ethersphere/swarm#341]
Hi there,

I've bumped into the following panic shortly after running a Swarm node.

#### System information

Geth version: 
```
Geth
Version: 1.8.3-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/lib/go-1.10
```
Commit hash : `166c3e7e5be09e1452df92137ca2fd1b7de71bab` (swarm-network-rewrite branch)

#### Expected behaviour
Swarm node runs without crashing.

#### Actual behaviour
Swarm node crashes shortly after being run

#### Steps to reproduce the behaviour
1. Run a Swarm Node with PSS enabled 
2. Connect other nodes to the node
3. Starting sending PSS messages through the network

#### Backtrace

````
panic: close of closed channel

goroutine 35 [running]:
github.com/ethereum/go-ethereum/swarm/storage.(*LDBStore).Put(0xc4202bc000, 0xc422ef3620)
	/home/ubuntu/go/src/github.com/ethereum/go-ethereum/swarm/storage/ldbstore.go:567 +0x3be
github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc420079220, 0xc422c36120)
	/home/ubuntu/go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:101 +0x244
github.com/ethereum/go-ethereum/swarm/storage.(*DBAPI).Put(0xc42053a6b0, 0xc422c36120)
	/home/ubuntu/go/src/github.com/ethereum/go-ethereum/swarm/storage/dbapi.go:51 +0x39
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc4201914d0)
	/home/ubuntu/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:209 +0x207
created by github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
	/home/ubuntu/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:50 +0xbe
````

**Comment by nonsense** [comment]
Hopefully this is solved with @samuil's fix. Closing, please re-open in case you see this again.
