### ISSUE TITLE
Fix panic in `removeOldest`

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#357]
```
swarm_8503 WARN [03-30|16:02:43.19524|swarm/storage/memstore.go:263]        purge memstore
swarm_8503 panic: nil
swarm_8503
swarm_8503 goroutine 23537 [running]:
swarm_8503 github.com/ethereum/go-ethereum/swarm/storage.(*MemStore).removeOldest(0xc4202e5ec0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/storage/memstore.go:295 +0x633
swarm_8503 github.com/ethereum/go-ethereum/swarm/storage.(*MemStore).Put(0xc4202e5ec0, 0xc425b54a80)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/storage/memstore.go:156 +0x93d
swarm_8503 github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).get(0xc42000c600, 0xc4226c7560, 0x20, 0xaa0, 0x0, 0xc4249419d0, 0x68)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:135 +0x181
swarm_8503 github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).GetOrCreateRequest(0xc42000c600, 0xc4226c7560, 0x20, 0xaa0, 0x0, 0x0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:145 +0xc1
swarm_8503 github.com/ethereum/go-ethereum/swarm/storage.(*DBAPI).GetOrCreateRequest(0xc4202512b0, 0xc4226c7560, 0x20, 0xaa0, 0xc425b548c0, 0x100)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/storage/dbapi.go:46 +0x4d
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*SwarmSyncerClient).NeedData(0xc423c3ba00, 0xc4226c7560, 0x20, 0xaa0, 0x0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/syncer.go:196 +0x51
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).handleOfferedHashesMsg(0xc422f51880, 0xc423676ea0, 0xc421d7b880, 0xd1ea40)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/messages.go:192 +0x264
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).HandleMsg(0xc422f51880, 0xd1ea40, 0xc423676ea0, 0xd1ea40, 0xc423676ea0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/stream.go:473 +0x14a
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).HandleMsg-fm(0xd1ea40, 0xc423676ea0, 0xf83800, 0xc4268687e0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/stream.go:382 +0x3e
swarm_8503 github.com/ethereum/go-ethereum/p2p/protocols.(*Peer).handleIncoming(0xc423aa4b20, 0xc4228ebba8, 0x0, 0x0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/p2p/protocols/protocol.go:260 +0x493
swarm_8503 github.com/ethereum/go-ethereum/p2p/protocols.(*Peer).Run(0xc423aa4b20, 0xc4228ebba8, 0x10de23f1b3d940e7, 0xd7cd17c72bda5232)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/p2p/protocols/protocol.go:202 +0x35
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Run(0xc4200d21e0, 0xc426754060, 0x0, 0x0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/stream.go:382 +0x164
swarm_8503 github.com/ethereum/go-ethereum/swarm/network/stream.(*Registry).Run-fm(0xc426754060, 0xc426754060, 0x19ffc20)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/swarm.go:162 +0x34
swarm_8503 github.com/ethereum/go-ethereum/swarm/network.(*Bzz).RunProtocol.func1(0xc4262c2f00, 0xf87820, 0xc424ae8000, 0x0, 0x0)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:225 +0x51f
swarm_8503 github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc424ae8000, 0xc4262c2f00, 0xf87820, 0xc424ae8000)
swarm_8503      /go/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
swarm_8503 created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
swarm_8503      /go/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x201
```

**Comment by nonsense** [comment]
Duplicate of https://github.com/ethersphere/go-ethereum/issues/342
