### ISSUE TITLE
Stream benchmarks are broken

### ISSUE THREAD

**Issue by janos** [ethersphere/swarm#382]
Currently, the benchmarks are failing on `swarm-network-rewrite` branch.

go test -v -run none -bench . ./swarm/network/stream -loglevel 0
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45cccf4]

goroutine 102 [running]:
github.com/ethereum/go-ethereum/swarm/network/stream.NewStreamerService(0xc4201d2540, 0xc4202d4270, 0x47babab, 0x8, 0xc4202e8498)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/common_test.go:84 +0x184
github.com/ethereum/go-ethereum/p2p/simulations/adapters.(*SimNode).Start.func1.1(0xc4201daf20, 0xc4202d5c50, 0xc42008b9d0, 0xc4201daf00, 0x2)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/p2p/simulations/adapters/inproc.go:261 +0x104
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc420112280, 0x0, 0x0)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/node/node.go:182 +0x42c
github.com/ethereum/go-ethereum/p2p/simulations/adapters.(*SimNode).Start(0xc4200f2480, 0x0, 0x0, 0x0)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/p2p/simulations/adapters/inproc.go:285 +0xd1
github.com/ethereum/go-ethereum/p2p/simulations.(*Network).startWithSnapshots(0xc4201a0100, 0xb51afb014b9d58f8, 0x5cbe0fe7bcdc756b, 0x8a801f788005ae79, 0xc3cb005b81dcb3c7, 0x1084f39b4e825bb3, 0xf01aa30f894f7508, 0x26e177e4c9f866d3, 0xd706700141bfe6cc, 0x0, ...)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/p2p/simulations/network.go:173 +0x223
github.com/ethereum/go-ethereum/p2p/simulations.(*Network).Start(0xc4201a0100, 0xb51afb014b9d58f8, 0x5cbe0fe7bcdc756b, 0x8a801f788005ae79, 0xc3cb005b81dcb3c7, 0x1084f39b4e825bb3, 0xf01aa30f894f7508, 0x26e177e4c9f866d3, 0xd706700141bfe6cc, 0xc42009b200, ...)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/p2p/simulations/network.go:159 +0x51
github.com/ethereum/go-ethereum/swarm/network/stream/testing.(*Simulation).Run(0xc4202e2320, 0x48750c0, 0xc420308000, 0xc4202d20f0, 0xc420063fa8, 0xc42006a800, 0xc420063fa8)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/testing/testing.go:186 +0xdc
github.com/ethereum/go-ethereum/swarm/network/stream.benchmarkDeliveryFromNodes.func4(0xc4202e2320, 0x48750c0, 0xc420308000, 0xc4202d20f0, 0xc42032a120, 0xc42032a240)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery_test.go:578 +0x50
created by github.com/ethereum/go-ethereum/swarm/network/stream.benchmarkDeliveryFromNodes
	/Users/janos/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery_test.go:577 +0x6de
exit status 2
FAIL	github.com/ethereum/go-ethereum/swarm/network/stream	0.070s
```

**Comment by janos** [comment]
Resolved by https://github.com/ethersphere/go-ethereum/pull/385.
