### ISSUE TITLE
Fix panic

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#533]
```
swarm_30402 DEBUG[05-10|14:33:50.62544|swarm/network/stream/messages.go:307] wanted batch length                      peer=e4804e2558a46909 stream=SYNC|0|h            from=4915358          to=18446744073709551615 lenhashes=32   l=1
swarm_30402 DEBUG[05-10|14:33:59.732075|swarm/storage/chunker.go:542]         lazychunkreader.read                     key=0cf2a29b08289d4b298e2dd84b40797fca4c467936409666ee9362b2cd06d78f
swarm_30402 DEBUG[05-10|14:33:59.732191|swarm/storage/chunker.go:405]         lazychunkreader.size                     key=0cf2a29b08289d4b298e2dd84b40797fca4c467936409666ee9362b2cd06d78f
swarm_30402 DEBUG[05-10|14:34:00.019418|swarm/network/stream/messages.go:307] wanted batch length                      peer=e4804e2558a46909 stream=SYNC|0|l            from=4915359          to=0                    lenhashes=32   l=1
swarm_30402 DEBUG[05-10|14:34:00.485454|swarm/network/stream/messages.go:307] wanted batch length                      peer=d2ea8b7fa5b0ed53 stream=SYNC|0|l            from=4915359          to=0                    lenhashes=32   l=1
swarm_30402 DEBUG[05-10|14:34:00.486133|swarm/network/stream/messages.go:307] wanted batch length                      peer=d2ea8b7fa5b0ed53 stream=SYNC|0|h            from=4915359          to=18446744073709551615 lenhashes=32   l=1
swarm_30402 DEBUG[05-10|14:34:00.627135|swarm/network/stream/messages.go:307] wanted batch length                      peer=e4804e2558a46909 stream=SYNC|0|h            from=4915359          to=18446744073709551615 lenhashes=32   l=1
swarm_30402 DEBUG[05-10|14:34:09.733079|swarm/storage/netstore.go:112]        NetStore.Get retry chunk                 key=701b109879be955e59e84338720805f917259e7bde6941eb88d2f7fb44ace079
swarm_30402 panic: runtime error: slice bounds out of range
swarm_30402
swarm_30402 goroutine 1780642 [running]:
swarm_30402 github.com/ethereum/go-ethereum/swarm/storage.ChunkData.Size(...)
swarm_30402     /go/src/github.com/ethereum/go-ethereum/swarm/storage/types.go:317
swarm_30402 github.com/ethereum/go-ethereum/swarm/storage.(*LazyChunkReader).join(0xc421e3b3b0, 0xc421390000, 0x1000, 0x8000, 0x0, 0x1000, 0x0, 0x20, 0x0, 0x0, ...)
swarm_30402     /go/src/github.com/ethereum/go-ethereum/swarm/storage/chunker.go:479 +0x4f6
swarm_30402 github.com/ethereum/go-ethereum/swarm/storage.(*LazyChunkReader).join.func1(0xc425f38020, 0x1008, 0x12e0, 0xc421e3b3b0, 0xc421838f60, 0x8000, 0xc42364a8b8, 0xc421838ea0, 0xc42364a8d0, 0xc421390000, ...)
swarm_30402     /go/src/github.com/ethereum/go-ethereum/swarm/storage/chunker.go:535 +0x20a
swarm_30402 created by github.com/ethereum/go-ethereum/swarm/storage.(*LazyChunkReader).join
swarm_30402     /go/src/github.com/ethereum/go-ethereum/swarm/storage/chunker.go:521 +0x333
```

cc @gbalint @janos

**Comment by janos** [comment]
This panic should be handled by https://github.com/ethersphere/go-ethereum/pull/711. It still does not solve the problem of having too short chunks, but it prevents panic, at least. @nonsense  could this issue be closed?
