### ISSUE TITLE
Fix panic - close of closed channel

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#570]
```
swarm_30399 DEBUG[05-20|11:43:21.431513|swarm/api/manifest.go:240]            manifest retrieved                       key=7ad90faf79734569eb0143a6e118ffcc3c54f864d3c7bcef0fc238b7223ad3c9
swarm_30399 DEBUG[05-20|11:43:21.431588|swarm/api/http/server.go:321]         handle.direct.upload                     ruid=4c8694ea
swarm_30399 DEBUG[05-20|11:43:21.431652|swarm/api/api.go:244]                 api.store                                size=205
swarm_30399 DEBUG[05-20|11:43:21.43174|swarm/storage/pyramid.go:207]         pyramid.chunker: Split()
swarm_30399 DEBUG[05-20|11:43:21.431926|swarm/storage/pyramid.go:387]         pyramid.chunker: prepareChunks           isAppend=false
swarm_30399 DEBUG[05-20|11:43:21.43255|swarm/storage/pyramid.go:287]         pyramid.chunker: processChunk()          id=1
swarm_30399 panic: close of closed channel
swarm_30399
swarm_30399 goroutine 32683403 [running]:
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc421529620, 0xc427793f80)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:134 +0x4ce
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*NetStore).Put(0xc420a47ca0, 0xc427793f80)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/netstore.go:170 +0x38
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).storeChunk(0xc424259740, 0xc427793f80)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:214 +0x84
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).Put(0xc424259740, 0xc424f34c00, 0xd5, 0x1008, 0x2, 0x7fb1991f5d90, 0x4414fa, 0xf1be98, 0xc4200de1e0)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:89 +0xbb
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processChunk(0xc421b175f0, 0x1, 0xc424259780)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:289 +0x10a
swarm_30399 github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processor(0xc421b175f0, 0x1)
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:279 +0x81
swarm_30399 created by github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).prepareChunks
swarm_30399     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:394 +0x157
```

**Comment by nonsense** [comment]
```
  1 swarm_30401 INFO [06-06|15:10:20.4186|swarm/api/http/server.go:985]         serving request                          ruid=c0f4c2b0 method=POST url=/bzz:/35e0e1210aa4c6e9    ee3b3d3410cc12ed83afd557cf4aa30fc53ff063b2d93a7d/digitalProfile.ked
  2 swarm_30401 DEBUG[06-06|15:10:20.418721|swarm/api/http/server.go:1020]        parsed request path                      ruid=c0f4c2b0 method=POST uri.Addr=35e0e1210aa4c6e    9ee3b3d3410cc12ed83afd557cf4aa30fc53ff063b2d93a7d uri.Path=digitalProfile.ked uri.Scheme=bzz
  3 swarm_30401 DEBUG[06-06|15:10:20.418797|swarm/api/http/server.go:1034]        handlePostFiles
  4 swarm_30401 DEBUG[06-06|15:10:20.418913|swarm/api/http/server.go:169]         handle.post.files                        ruid=c0f4c2b0
  5 swarm_30401 DEBUG[06-06|15:10:20.429279|swarm/api/http/server.go:192]         resolved key                             ruid=c0f4c2b0 key=35e0e1210aa4c6e9ee3b3d3410cc12ed    83afd557cf4aa30fc53ff063b2d93a7d
  6 swarm_30401 DEBUG[06-06|15:10:20.429329|swarm/storage/chunker.go:405]         lazychunkreader.size                     key=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa3    0fc53ff063b2d93a7d
  7 swarm_30401 DEBUG[06-06|15:10:20.554219|swarm/storage/localstore.go:134]      closing ReqC                             addr=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa    30fc53ff063b2d93a7d
  8 swarm_30401 DEBUG[06-06|15:10:20.554333|swarm/storage/chunker.go:542]         lazychunkreader.read                     key=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa3    0fc53ff063b2d93a7d
  9 swarm_30401 DEBUG[06-06|15:10:20.554359|swarm/storage/chunker.go:405]         lazychunkreader.size                     key=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa3    0fc53ff063b2d93a7d
 10 swarm_30401 DEBUG[06-06|15:10:20.55438|swarm/api/manifest.go:240]            manifest retrieved                       key=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa30    fc53ff063b2d93a7d
 11 swarm_30401 DEBUG[06-06|15:10:20.554426|swarm/api/http/server.go:322]         handle.direct.upload                     ruid=c0f4c2b0
 12 swarm_30401 DEBUG[06-06|15:10:20.554444|swarm/api/api.go:245]                 api.store                                size=591
 13 swarm_30401 DEBUG[06-06|15:10:20.554479|swarm/storage/pyramid.go:207]         pyramid.chunker: Split()
 14 swarm_30401 DEBUG[06-06|15:10:20.55449|swarm/storage/pyramid.go:387]         pyramid.chunker: prepareChunks           isAppend=false
 15 swarm_30401 DEBUG[06-06|15:10:20.554522|swarm/storage/pyramid.go:287]         pyramid.chunker: processChunk()          id=1
 16 swarm_30401 DEBUG[06-06|15:10:20.561587|swarm/storage/localstore.go:134]      closing ReqC                             addr=35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa    30fc53ff063b2d93a7d
 17 swarm_30401 panic: close of closed channel
 18 swarm_30401
 19 swarm_30401 goroutine 32122804 [running]:
 20 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc422386000, 0xc422e1b100)
 21 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:135 +0x575
 22 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*NetStore).Put(0xc42236acc0, 0xc422e1b100)
 23 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/netstore.go:175 +0x38
 24 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).storeChunk(0xc42313c200, 0xc422e1b100)
 25 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:214 +0x84
 26 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*hasherStore).Put(0xc42313c200, 0xc422348000, 0x257, 0x1008, 0x2, 0xc424e40180, 0x44172a, 0xf25f20, 0x1a)
 27 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/hasherstore.go:89 +0xbb
 28 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processChunk(0xc422d33520, 0x1, 0xc42313c240)
 29 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:289 +0x10a
 30 swarm_30401 github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).processor(0xc422d33520, 0x1)
 31 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:279 +0x81
 32 swarm_30401 created by github.com/ethereum/go-ethereum/swarm/storage.(*PyramidChunker).prepareChunks
 33 swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/storage/pyramid.go:394 +0x157
```

This should help us solve it.

**Comment by nonsense** [comment]
Looks like uploading a very small file should be triggering this panic.

**Comment by nonsense** [comment]
This looks like a race condition between the two calls to `lazychunkreader.size`, but I haven't been able to reproduce or understand fully. Locally I manage to get only one call to `closing ReqC`.

cc @janos

**Comment by cobordism** [comment]
update: Anton and I discovered that it is a race condition that is only triggered sometimes when the uploaded content that is to be added to a manifest at a certain path is the manifest itself.

This is why in the stack trace above, the pyramid chunker (which is processing the content to be saved) is calling a `Put` on `35e0e1210aa4c6e9ee3b3d3410cc12ed83afd557cf4aa`, which is also the resolved manifest.
