### ISSUE TITLE
Panic in getResolveValidator

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#659]
Reported by @agazso

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46ca4f6]

goroutine 12 [running]:
github.com/ethereum/go-ethereum/swarm/api.(*MultiResolver).getResolveValidator(0x0, 0xc4244f1750, 0xd, 0x0, 0xc4204d8e80, 0x20, 0x20, 0x0)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/api/api.go:191 +0x26
github.com/ethereum/go-ethereum/swarm/api.(*MultiResolver).ValidateOwner(0x0, 0xc4244f1750, 0xd, 0x44ba8f5f39bab270, 0xa76e7955eb363426, 0xeb3634267d2b245c, 0x7d2b245ca76e7955, 0xc4204d8e00, 0xc4200fd4a0)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/api/api.go:159 +0x5a
github.com/ethereum/go-ethereum/swarm/storage.(*ResourceHandler).checkAccess(0xc4203fe5a0, 0xc4244f1750, 0xd, 0x44ba8f5f39bab270, 0xa76e7955eb363426, 0x270815907d2b245c, 0xd26e3d33b8781de5, 0xb7c354e6d0a0a2c4, 0xb21bf9429456f750)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/storage/resource.go:313 +0x65
github.com/ethereum/go-ethereum/swarm/storage.(*ResourceHandler).Validate(0xc4203fe5a0, 0xc424291dc0, 0x20, 0x240, 0xc4220fa500, 0xa0, 0xa0, 0xc4203fc100)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/storage/resource.go:289 +0x30e
github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc4203fc120, 0xc422163d80)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:102 +0xd4
github.com/ethereum/go-ethereum/swarm/storage.(*DBAPI).Put(0xc4204d7e50, 0xc422163d80)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/storage/dbapi.go:51 +0x39
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc4203fc150)
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:228 +0x230
created by github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
    /Users/attila/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:60 +0xbe
```

**Comment by janos** [comment]
This should be resolved by https://github.com/ethersphere/go-ethereum/pull/635. The trace is the same. Do we know if the panic is with the latest code?

**Comment by gbalint** [comment]
It was with older code, so let's close this
