### ISSUE TITLE
panic: not in db?

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#681]
```
swarm_30401 panic: not in db? addr 17da3068dd7e4399f33bdac5a2c1c3932836b743f4b117bca37be966b3a89529 chunk <nil>
swarm_30401
swarm_30401 goroutine 87 [running]:
swarm_30401 github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc42140c660)
swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:215 +0x38e
swarm_30401 created by github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
swarm_30401     /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:59 +0xbe
```

**Comment by nonsense** [comment]
@gbalint closing this for now as we got rid of the panic. We should be monitoring the errors and see what we can do about it.

**Comment by gbalint** [comment]
@nonsense Ok, I opened a new issue for the error, which still happens unfortunately: https://github.com/ethersphere/go-ethereum/issues/694
