### ISSUE TITLE
bmt: panic index out of range

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#785]
Crash on `2eedbe799f5eb8766e4808d8a1810cc1c90c4b93`

```
WARN [07-11|23:36:20.043] 3f8383f8: handshake failed with remote peer a6747ae4: Handshake erro
WARN [07-11|23:36:48.072] 3f8383f8: handshake failed with remote peer 39207f5a: Handshake erro
panic: runtime error: index out of range

goroutine 2218 [running]:
github.com/ethereum/go-ethereum/swarm/bmt.(*Hasher).writeSection(0xc4228d5370, 0x42, 0xc4214a1
	/home/lash/data/src/.go/src/github.com/ethereum/go-ethereum/swarm/bmt/bmt.go:422 +0x1c
created by github.com/ethereum/go-ethereum/swarm/bmt.(*Hasher).Write
	/home/lash/data/src/.go/src/github.com/ethereum/go-ethereum/swarm/bmt/bmt.go:369 +0x16
```

**Comment by zelig** [comment]
BMT is set for max datasize `SegmentCount * HashSize`
for 4k chunks this means we default to 

https://github.com/ethersphere/go-ethereum/blob/develop/swarm/bmt/bmt.go#L59

Using the DefaultHasher (BMT) and bmt.SegmentCount we set the hasher 

https://github.com/ethersphere/go-ethereum/blob/develop/swarm/storage/types.go#L117

I conclude this is not a bug of bmt and close

**Comment by cobordism** [comment]
> I conclude this is not a bug of bmt and close

who cares what it is a bug of?? swarm crashes constantly now. This needs to be fixed urgently before the next release is triggered.

```
panic: runtime error: index out of range

goroutine 22296 [running]:
github.com/ethereum/go-ethereum/swarm/bmt.(*Hasher).writeSection(0xc4283a36b0, 0x3fc, 0xc421e60dc0, 0x40, 0x40, 0x1)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/bmt/bmt.go:422 +0x1ca
created by github.com/ethereum/go-ethereum/swarm/bmt.(*Hasher).sum
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/swarm/bmt/bmt.go:319 +0xc1
```
