### ISSUE TITLE
Slice out of bounds panic

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#807]
```
panic: runtime error: slice bounds out of range

goroutine 72 [running]:
github.com/ethereum/go-ethereum/swarm/storage/mru.(*Handler).parseUpdate(0xc4200e6120, 0xc4203717d0, 0x2e, 0x2e, 0x20, 0x20, 0xc422e7c500, 0xc4203717d0, 0xc424cb9880, 0xfb2b
60, ...)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/mru/resource.go:740 +0xd7c
github.com/ethereum/go-ethereum/swarm/storage/mru.(*Handler).Validate(0xc4200e6120, 0xc42157c180, 0x20, 0xe80, 0xc4203717d0, 0x2e, 0x2e, 0xc423d80400)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/mru/resource.go:288 +0x6a
github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Put(0xc42104e420, 0xc4285eea00)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:108 +0xed
github.com/ethereum/go-ethereum/swarm/storage.(*DBAPI).Put(0xc421048510, 0xc4285eea00)
        /go/src/github.com/ethereum/go-ethereum/swarm/storage/dbapi.go:51 +0x39
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc42104e450)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:227 +0x2e6
created by github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
        /go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:58 +0xbe
```

**Comment by nonsense** [comment]
@nolash @jpeletier does this ring a bell? Do you know if this is still relevant, or fixed?

**Comment by jpeletier** [comment]
There is no `parseUpdate` anymore in `Handler.Validate()`, and serializers where refactored from the ground up, so I am sure this panic can't happen now with the code in `master`

**Comment by nolash** [comment]
We had panics with invalid chunks triggering panics a couple of weeks back as I recall?

**Comment by nonsense** [comment]
OK, I will keep an eye on the logs and close this for now. Thanks!
