### ISSUE TITLE
Rare leveldb panic

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#919]
It happens very rarely, I can't reproduce. It happened to me running snapshot tests:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4268629]

goroutine 5844 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).NewIterator(...)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:54
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc424aefba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42b330390, 0xc4306d3200)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:54 +0x2d9
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc424aefba0, 0x0, 0x0, 0x0, 0x0, 0xc, 0x0, 0x0, 0x4cc6738)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:79 +0x99
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc424aefba0, 0x0, 0x0, 0x0, 0x0)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:887 +0x183
github.com/ethereum/go-ethereum/swarm/storage.(*LDBDatabase).NewIterator(0xc4201dded8, 0xa, 0xa)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/storage/database.go:85 +0x8c
github.com/ethereum/go-ethereum/swarm/storage.(*LDBStore).SyncIterator(0xc427d55680, 0x1, 0xffffffffffffffff, 0xc4292fe704, 0xc42a059920, 0x0, 0x0)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/storage/ldbstore.go:832 +0x167
github.com/ethereum/go-ethereum/swarm/storage.(*LocalStore).Iterator(0xc4281a3560, 0x1, 0xffffffffffffffff, 0x4, 0xc42a059920, 0x4752d01, 0xc42a059920)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/storage/localstore.go:180 +0x56
github.com/ethereum/go-ethereum/swarm/storage.(*NetStore).Iterator(0xc4281a3620, 0x1, 0xffffffffffffffff, 0x4, 0xc42a059920, 0x4cc6738, 0x0)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/storage/netstore.go:107 +0x5b
github.com/ethereum/go-ethereum/swarm/network/stream.(*SwarmSyncerServer).SetNextBatch(0xc43090ce80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/syncer.go:131 +0x34f
github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).SendOfferedHashes(0xc428c88700, 0xc43092e300, 0x0, 0x0, 0x0, 0x0)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/peer.go:164 +0xf6
github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).handleSubscribeMsg.func2(0xc428c88700, 0xc43092e300, 0x0, 0x0)
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/messages.go:119 +0x67
created by github.com/ethereum/go-ethereum/swarm/network/stream.(*Peer).handleSubscribeMsg
	/Users/gbalint/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/messages.go:118 +0x4d7
```

**Comment by gbalint** [comment]
Can't reproduce, let's reopen if happens again
